package com.jc.output;

import com.jc.bean.Format;

import java.util.List;

/*
* The user of this class can use the data generated by inputHandler
* and calculatorCore to assemble the output string and
* print it on console by log4j.info()
* */
public interface OutputHandler {

    /**
     * @param combination result from calculator core
     * @param format Format bean corresponding to the combination
     * it will assemble the output str
     * remind it can only build one output corresponding to the format which pass on
     * so iteratively invoke this method if there are multiple required format submission
     */
    void buildOutputStr(List<Integer> combination, Format format);

    /**
     * Using this method to print outputStr on console
     * remind invoke this method after all single itemOutput corresponding to format submission
     * have been assembled
     */
    void outputResult();
}
